### ISSUE TITLE
Turtle texture not changed

### ISSUE THREAD

**Issue by jupiterbjy** [sashakoshka/ccc#2]
# ComputerCraft Create

Turtle texture and turtle model's model not being applied.

![image](https://github.com/sashakoshka/ccc/assets/26041217/9e3d0059-2136-4c19-a363-2f1cdaa66b09)

<br>

# ComputerCreate

[The other one](https://modrinth.com/resourcepack/computercreate)'s turtle modem model still works, but not turtle itself too.

![image](https://github.com/sashakoshka/ccc/assets/26041217/eecb6eb0-c1b3-4c03-95a4-110af6a89439)

---

<br>

Seems like naming changed in CC:Tweaked recently? I know nothing about how resource packs works but seems like naming quite differ between two packs.

![image](https://github.com/sashakoshka/ccc/assets/26041217/183f720c-c756-4096-8270-6a45f0de6766)

**Comment by sashakoshka** [comment]
I am aware of this issue, going to fix it soon

**Comment by sashakoshka** [comment]
https://github.com/sashakoshka/ccc/releases/tag/v5.0.0

**Comment by jupiterbjy** [comment]
![image](https://github.com/sashakoshka/ccc/assets/26041217/7f79f37b-8efe-4f7f-8fd5-e9dfcea7ec14)

Happy turtle is a good turtle, thx for fast fix, now I can't play without this resource pack.
